2023-11-23 14:54:18,332 (80569/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-23 14:54:18,332 (80569/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-23 14:54:18,335 (80569/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2023-11-23 14:57:19,985 (80900/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-23 14:57:19,985 (80900/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-23 14:57:19,988 (80900/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: "123456"\n'
2023-11-23 14:57:32,154 (80925/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-23 14:57:32,154 (80925/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-23 14:57:32,366 (80925/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: nodename nor servname provided, or not known\n'
2023-11-23 14:58:32,531 (81010/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-23 14:58:32,531 (81010/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-23 14:58:44,818 (81038/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-23 14:58:44,818 (81038/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-23 16:38:57,722 (87006/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-23 16:38:57,722 (87006/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-23 16:52:20,375 (87006/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) quit', error: SyntaxError('syntax error at or near "quit"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) quit\n                                                                ^')
2023-11-23 16:52:20,378 (87006/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "quit"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) quit\n                                                                ^\n'
2023-11-23 16:52:40,327 (87006/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) quit ALL', error: SyntaxError('syntax error at or near "quit"\nLINE 1: ...AIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) quit ALL\n                                                               ^')
2023-11-23 16:52:40,328 (87006/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "quit"\nLINE 1: ...AIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) quit ALL\n                                                               ^\n'
2023-11-23 16:52:50,839 (87006/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) exit', error: SyntaxError('syntax error at or near "exit"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) exit\n                                                                ^')
2023-11-23 16:52:50,839 (87006/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "exit"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) exit\n                                                                ^\n'
2023-11-23 16:52:58,179 (87006/MainThread) pgcli.pgexecute ERROR - sql: 'EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) q', error: SyntaxError('syntax error at or near "q"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) q\n                                                                ^')
2023-11-23 16:52:58,180 (87006/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "q"\nLINE 1: EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) q\n                                                                ^\n'
2023-11-23 17:18:30,365 (90291/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-23 17:18:30,365 (90291/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-23 22:26:30,501 (90291/MainThread) pgcli.pgexecute ERROR - sql: 'qui', error: SyntaxError('syntax error at or near "qui"\nLINE 1: qui\n        ^')
2023-11-23 22:26:30,504 (90291/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "qui"\nLINE 1: qui\n        ^\n'
2023-11-23 22:38:18,060 (12467/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-23 22:38:18,061 (12467/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-11-25 16:27:16,977 (12467/MainThread) pgcli.pgexecute ERROR - sql: 'select * FROM conversation', error: UndefinedTable('relation "conversation" does not exist\nLINE 1: select * FROM conversation\n                      ^')
2023-11-25 16:27:16,981 (12467/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "conversation" does not exist\nLINE 1: select * FROM conversation\n                      ^\n'
2023-11-28 21:04:12,520 (81685/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-11-28 21:04:12,520 (81685/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-12-01 11:32:54,195 (24335/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-12-01 11:32:54,196 (24335/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-12-02 16:44:23,133 (51756/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-12-02 16:44:23,133 (51756/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-12-02 17:03:46,754 (60901/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-12-02 17:03:46,754 (60901/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-12-02 17:36:57,485 (73759/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-12-02 17:36:57,485 (73759/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-12-02 17:55:27,153 (73759/MainThread) pgcli.pgexecute ERROR - sql: 'quitr', error: SyntaxError('syntax error at or near "quitr"\nLINE 1: quitr\n        ^')
2023-12-02 17:55:27,157 (73759/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 737, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "quitr"\nLINE 1: quitr\n        ^\n'
2023-12-02 18:03:05,002 (85071/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-12-02 18:03:05,002 (85071/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-12-02 18:03:11,535 (85071/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 670, in connect\n    pgexecute = PGExecute(\n                ^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection failed: :1), port 5432 failed: FATAL:  password authentication failed for user "postgres"\n'
2023-12-02 18:03:13,753 (85086/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-12-02 18:03:13,753 (85086/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-12-22 11:33:03,052 (17665/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-12-22 11:33:03,052 (17665/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-12-22 11:33:03,056 (17665/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 738, in connect\n    raise ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2023-12-22 11:34:57,170 (18068/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-12-22 11:34:57,170 (18068/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2023-12-22 11:35:18,634 (18125/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2023-12-22 11:35:18,634 (18125/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
